[package]
name = "lag-crusher"
version = "1.1.2"
description = "Lag Crusher"
authors = ["TH4RU5H4"]
edition = "2021"

[lib]
name = "lag_crusher_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
